# Initial project setup

# --- !Ups

CREATE TABLE `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(60) NOT NULL,
  `nickname` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  UNIQUE (`nickname`),
  PRIMARY KEY (`id`));

CREATE TABLE `post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  `image` VARCHAR(60) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (`slug`),
  PRIMARY KEY (`id`));

CREATE TABLE `comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `comment_id` INT UNSIGNED NULL,
  `comment` VARCHAR(256) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

INSERT INTO `user` (`fullname`, `nickname`, `password`) VALUES
('Samus Aran', 'cold_as_ice_beam', '$2a$10$IkTr6yVfcwxIBcfrzfK/j./lCqfNN9bvm86WtiTxv.f2ca409amG.'),
('Mega Man', 'master_blaster', '$2a$10$1Ryx4ja8UdDwmFoX1TzSFeMJlmaYeZ3195F0GQkrq6u86AlhypV8q'),
('Simon Belont', 'whip_it_good', '$2a$10$RehsMHnjcRi1DWZv7OqJK.SFTadpaDvU3KUdER021NjnLin6OlcXu'),
('Kid Icarus', 'mr_pit', '$2a$10$jgm4eurIXXL2sRnIdGp5quwVZ2Tc.DcZW/bMNo1hyxAx1edTxEhN6'),
('Glass Joe', 'one_99', '$2a$10$sCj/ZQ4gh9QMOdNmRflafuDUCP8yBy9kGbKw/ZMBcXYkCyVm5sytS'),
('Princess Zelda', 'so_sleepy', '$2a$10$UpYppRnajiXqxuTXfnbriOC8F/AcKbH6G45VwIBlbqL/ykKNEdPNy'),
('Donkey Kong', 'banana_slamma', '$2a$10$FKKPMM745gcJeDmZ9gjLR.ZKk0ES9Rsg6T1Pck2xRWQzKipBWjB6u'),
('Mario Mario', 'its_a_me', '$2a$10$1PunzImkUoGFdsb7HboL/OQTvVQNxuj2D0HEiOR5ex6fQv4NLCJhq');

INSERT INTO `post` (`user_id`, `title`, `slug`, `image`, `content`) VALUES
(8, 'Battletoads in Super Easy', 'battletoads-is-super-easy', 'battletoads.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in lectus molestie, consectetur velit vitae, feugiat elit. Aenean finibus velit vel lacinia porttitor. Aenean suscipit orci nec risus iaculis, at faucibus lacus eleifend. Proin in sollicitudin tortor, eu rhoncus nulla. Cras ultrices lectus non ligula vulputate posuere. Aenean a mollis diam. Sed sit amet semper lectus. Nulla non cursus nibh.</p><p>Nunc urna massa, consequat condimentum sem in, porta tristique est. Vestibulum id dolor lectus. Quisque tristique, purus nec lobortis pharetra, orci felis sollicitudin eros, non varius nisi libero vel neque. Praesent imperdiet interdum mi sit amet rhoncus. Praesent facilisis sapien quis leo ornare, id finibus neque porttitor. Quisque ut tincidunt ligula. Quisque consectetur, metus at suscipit tempor, est libero varius sem, varius placerat mi massa ut ex.</p><p>Sed quis leo nec velit dictum dignissim eu eu risus. Nulla facilisi. Maecenas maximus interdum leo, in venenatis est ultricies vel. Ut ipsum urna, facilisis quis egestas ac, laoreet vitae enim. Aliquam vel lectus quis libero volutpat aliquam. Donec dignissim dapibus diam, a porta orci. Vivamus commodo augue eget massa imperdiet mollis. Vivamus luctus consectetur ipsum, vitae tempus purus pretium at. Mauris vitae ornare turpis. Ut non turpis nec mi bibendum aliquet. Maecenas facilisis mi mi, ac rhoncus sapien pharetra non. Etiam vitae suscipit dui. Maecenas cursus nunc quis sollicitudin congue. Etiam fermentum elit sit amet elit pulvinar, rhoncus tristique odio lacinia.</p>'),
(2, 'Mario Bros Zapper Speedrun', 'mario-bros-zapper-speedrun', 'zapper.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis dolor et nisi congue, ut fermentum dui sagittis. Sed aliquet efficitur dui, vel tempus erat feugiat non. Fusce vulputate urna felis, quis varius nulla placerat a. Mauris sit amet tincidunt leo, nec posuere felis. Mauris lectus augue, gravida id nulla id, elementum tempor lorem. Pellentesque vel mauris et urna vulputate posuere. Nullam dictum ac massa non pellentesque. Cras sed lacinia lacus, et sodales magna. Cras vitae tempus sapien. Curabitur hendrerit nisi odio. Fusce at aliquam massa. Donec sodales, leo eu ultricies dapibus, est tellus iaculis odio, ac tempus eros felis ac massa. Quisque porta lorem ac nulla facilisis, vitae pellentesque nisi scelerisque.</p><p>Aliquam rutrum augue risus, ac dignissim nunc aliquet vel. Morbi porta vulputate metus, eu faucibus lacus aliquam ut. Proin id malesuada turpis. Quisque auctor eu nisi sit amet lacinia. Praesent varius, mauris quis lacinia iaculis, elit nibh bibendum quam, vel lacinia metus enim at mi. Fusce nisl tellus, tempor in massa ac, rhoncus sodales diam. In cursus neque in augue tempor semper. Suspendisse non vehicula neque, vel sollicitudin justo. Morbi eget metus a sem tempus facilisis. Ut sodales urna vel metus vulputate, at tempor orci semper.</p><p>Curabitur maximus sapien ut libero tempus ultricies. Suspendisse arcu elit, suscipit at sapien a, molestie malesuada enim. In et laoreet lorem. Suspendisse potenti. Quisque mattis mollis dolor, ac scelerisque turpis ultrices ut. Nullam a lorem neque. Sed pulvinar lacus in magna mollis venenatis. Ut aliquet, sem vitae pretium pulvinar, magna tortor scelerisque nunc, at vulputate nibh ex vel nibh. Cras dictum diam libero, vitae efficitur dui vehicula at. Phasellus a diam leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus sed nunc eget diam cursus elementum eu vitae tortor. Maecenas non dui quis lorem blandit mollis.</p><p>Nunc mollis at ex a varius. Etiam eget volutpat odio, vitae fermentum arcu. Ut lacus augue, interdum nec tellus quis, dignissim pellentesque urna. Aliquam eget nulla malesuada sem imperdiet lacinia a et nisl. Sed faucibus turpis at lorem consectetur, ornare sagittis eros blandit. Duis ligula nibh, cursus vitae lacus ac, aliquam ultrices nulla. Nullam eleifend ex erat, pharetra consectetur neque placerat eget.</p>'),
(7, 'Dr. Wily''s Top Ten Favorite Robot Masters', 'dr-wilys-top-ten-favorite-robot-masters', 'megaman.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit nec nulla vulputate finibus. Aenean consectetur pulvinar rhoncus. Aliquam ullamcorper, nunc eget fringilla molestie, libero velit gravida massa, eget maximus nunc risus sit amet nisi. Nullam tempus diam at quam tempor, nec tempus tellus accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris nibh ipsum, tempus quis purus commodo, dictum fermentum velit. Proin lacinia mi eget massa sagittis venenatis. Nunc sed hendrerit ex. Mauris congue felis eu iaculis ultrices. Aenean sed enim eget ligula efficitur aliquam at eget tellus.</p><p>In dapibus dui congue nulla suscipit molestie. Quisque fringilla porttitor sem. Sed hendrerit ex erat, sit amet interdum ipsum tincidunt et. Donec cursus dictum mauris, eu faucibus massa sagittis eget. Duis ac sodales magna. Sed quam tortor, cursus nec malesuada at, tempor ut libero. Vivamus dignissim sodales venenatis. Nunc semper dolor sed molestie lobortis. Mauris vestibulum sapien ut lacus lacinia egestas. Nunc ullamcorper nisi et nunc tempus vulputate. Sed dapibus tincidunt magna venenatis tempor. Duis eu mi at eros tincidunt scelerisque non nec diam. Maecenas at elementum ante, in consectetur eros. Phasellus id rhoncus elit. Nunc accumsan urna ac turpis cursus, et porta nisl facilisis.</p><p>Sed sit amet leo vel lacus egestas maximus. Mauris ornare erat ut nulla molestie dignissim. Nam cursus nisi id lorem pulvinar, tempor malesuada orci efficitur. Maecenas tempus nisi dolor, non vestibulum nunc aliquet at. Sed mattis suscipit turpis ac vestibulum. Cras auctor est eget scelerisque malesuada. Phasellus tincidunt lectus augue, ut ultrices risus venenatis vel. Curabitur nec mi sed felis posuere hendrerit. Praesent lectus metus, auctor eu tincidunt quis, placerat vel purus. Nulla fermentum nulla id dignissim mattis. Quisque libero ipsum, ultricies eget interdum vel, hendrerit eu ligula. Fusce justo justo, cursus nec quam id, pulvinar scelerisque mi. Nullam luctus ante ac nisi pretium, ut volutpat turpis lobortis. Aliquam ullamcorper augue non tortor varius semper. Nullam id felis aliquet, commodo libero ac, cursus urna. Aliquam accumsan nisi non turpis sagittis, at ultricies nisi elementum.</p>'),
(3, 'Trevor Belmont''s New Whip', 'trevor-belmonts-new-whip', 'simon.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tempus, elit ut sollicitudin mollis, nisl nisl feugiat erat, ut finibus ante lectus posuere massa. Suspendisse nec molestie mauris. Suspendisse vestibulum augue ipsum, sit amet iaculis augue rutrum convallis. Sed tristique, velit vestibulum pulvinar gravida, elit nisl cursus erat, non tempus nisl libero iaculis libero. Maecenas in lobortis urna. Curabitur vitae magna eget orci facilisis consectetur faucibus nec justo. Aliquam sem mauris, posuere ac purus et, laoreet vulputate magna. Aliquam sed tempus ex, vel accumsan leo. Fusce a leo nec arcu luctus accumsan vel eget mauris. Aenean quis fermentum lorem, in venenatis erat. Donec quis vulputate justo. Proin volutpat nisl blandit ligula rhoncus eleifend. Suspendisse sodales justo vel fringilla rhoncus. Donec porta urna velit.</p><p>Morbi orci ante, sollicitudin nec commodo sit amet, eleifend eu arcu. Morbi ut vehicula mi. Etiam volutpat imperdiet libero iaculis maximus. Donec et est ligula. Donec suscipit molestie lacus ut auctor. Donec a eros a magna mollis accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eget facilisis mi. Nullam in efficitur elit, eget venenatis lorem. Integer pulvinar tortor sollicitudin risus consectetur pellentesque. Proin sed scelerisque dolor.</p><p>Integer convallis imperdiet ante, sed commodo felis lobortis et. Quisque ac venenatis elit. Aliquam euismod lorem sem, in congue erat elementum vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras quam ante, egestas et ex laoreet, volutpat pulvinar massa. Suspendisse et tincidunt tortor, eget feugiat lectus. Ut justo odio, hendrerit vel varius id, blandit et odio. Morbi imperdiet lectus magna, eu dictum urna aliquet sit amet. Proin tempor dolor non odio blandit, sed ullamcorper nunc mollis. Aliquam erat volutpat. Pellentesque vitae nibh elit. Nulla iaculis arcu nisi, eu rhoncus lectus mollis quis. Curabitur egestas vitae dolor at finibus.</p>'),
(4, '6502 Assembly For Dummies', '6502-assembly-for-dummies', 'assembly.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc accumsan, dolor vitae consequat pulvinar, velit massa sollicitudin arcu, eget malesuada magna orci in nisi. Nullam iaculis in quam in iaculis. Sed odio est, tincidunt eu dolor vitae, molestie sagittis dui. Cras augue risus, sagittis a tellus sit amet, semper pretium nisl. Ut ultricies interdum diam, et facilisis sapien ultricies sit amet. Vivamus faucibus enim quis neque mattis finibus eu eu enim. Phasellus non sapien tempus eros consequat semper sit amet eu tellus.</p><p>Cras efficitur nulla eget neque congue, non blandit enim tincidunt. Duis vitae ullamcorper velit, eu blandit tellus. Vestibulum commodo nisl leo, nec pulvinar ligula vulputate ac. Mauris sagittis libero in finibus faucibus. Ut sit amet arcu ac lectus congue blandit. Morbi sed mi nisi. Vivamus in turpis pretium, mattis purus ut, sollicitudin augue.</p><p>Morbi quis ipsum egestas, hendrerit justo ut, rutrum tellus. Cras at fringilla elit, in ultrices libero. In eget blandit ex. Cras sit amet euismod ipsum. Ut eleifend arcu lectus, ut egestas est imperdiet in. Morbi et maximus nulla, quis pharetra tortor. Donec et molestie augue. Phasellus sodales dolor vitae neque pellentesque ultrices. Nulla interdum rutrum massa in pellentesque.</p><p>Fusce in est arcu. Praesent accumsan tortor lorem, at fringilla diam tempus nec. Duis vitae tellus sodales, fringilla turpis ut, sagittis est. Vivamus euismod lectus convallis arcu tincidunt, et faucibus massa gravida. Nunc fermentum libero vel ante iaculis accumsan. Mauris quis aliquet purus. Praesent quis ipsum nunc. Phasellus interdum hendrerit nulla in dictum. Nulla vulputate eu diam eu efficitur. Phasellus ut lacus ultricies neque iaculis elementum non eu nulla. Etiam tempus lorem sit amet dui ultricies, non fringilla nunc cursus. Fusce et imperdiet tortor, ac bibendum ex. In hac habitasse platea dictumst.</p>'),
(6, 'Floyd Mayweather''s Punch-Out!! Sneak Peak', 'floyd-mayweathers-punch-out-sneak-peak', 'punchout.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue mauris justo, ut vestibulum ligula hendrerit vel. Pellentesque vitae ullamcorper metus. Donec quis velit sit amet lectus tempor blandit in vitae elit. Ut leo urna, porttitor vitae ligula eget, vestibulum scelerisque sem. In at auctor felis. Donec efficitur, nisl id aliquam accumsan, lectus felis molestie tortor, in semper erat nisl et nunc. Fusce iaculis ornare orci at consequat. Duis mattis id augue in congue.</p><p>Phasellus a libero posuere, tristique turpis ut, malesuada leo. Donec vel elit placerat purus tempus porta. Sed vitae risus a ligula sagittis consequat. Vestibulum lectus libero, consectetur sit amet ligula ac, ultrices molestie enim. Vestibulum vehicula, nulla id dictum ullamcorper, mauris elit gravida ligula, in volutpat orci arcu aliquet diam. Suspendisse interdum sed lorem feugiat tristique. Donec porttitor mauris in turpis fermentum suscipit. Aenean nec semper tortor.</p>');

INSERT INTO `comment` (`post_id`, `user_id`, `comment_id`, `comment`) VALUES
(1, 5, NULL, 'First comment! Hooray!'),
(1, 1, 1, 'You "beat me to the punch" :D'),
(2, 1, NULL, 'Is this even possible?'),
(2, 8, NULL, 'Impressive!!!!!!!!'),
(3, 7, NULL, 'My favorite is Skull Man from Mega Man 4!'),
(3, 2, 5, 'I fought him. I won.'),
(4, 1, NULL, 'I''m more interested in Richter''s whip and abilities. Trevor was slow and needed friends to help him beat dracula.'),
(4, 4, 7, 'I''m doing a post on him next week.  Stay tuned!'),
(5, 7, NULL, 'Boooooooooring!!!!!'),
(5, 6, NULL, 'ZZZZZzzzzzzzzz'),
(6, 3, NULL, 'You won''t even need to use the punch button haha!!'),
(6, 5, 11, 'Maybe there''s a chance I could beat Floyd?'),
(6, 4, 12, 'Joe ... really? YOU?! You''re only win was against Nick Bruiser and that was a total accident (he would annihilate you if there was ever a rematch).');

# --- !Downs

DROP TABLE `user`;
DROP TABLE `post`;
DROP TABLE `comment`;
